### ISSUE TITLE
Bug TRP 3 Names

### ISSUE THREAD

**Issue by Melyria** [Ellypse/Total-RP-3#108]
Hello !

I use TRP 3 latest version (1.3.2.1), and I just found a little bug. If your name is in the name of another player (here my name is Mal and my friend Malathria), TRP is a little confused.

Here's the screen :

![inkedwowscrnshot_032418_232749_li](https://user-images.githubusercontent.com/37755165/37869639-a68f205c-2fbb-11e8-8b22-e55048d37293.jpg)

Have a good day !

**Comment by Solanya** [comment]
Oh no. Merci pour le retour, je traduis en anglais pour les non-francophones.

**If your character's name is a prefix of another character's name, it will color and add the icon to the prefix corresponding to your name as if it was your own name. This happens with non-custom emotes - from the prefix player targetting the other. It doesn't happen with custom emotes.**

**Comment by Melyria** [comment]
Yes, I didn't see that the tread was in English, so I translated ^^

**Comment by Solanya** [comment]
Just looked at the code and did some testing, it's unfortunately a bug on Blizzard's end with the class coloring function that TRP hooks onto.
Using the class colouring in emotes with TRP disabled will put the class colour on the prefix.
![image](https://user-images.githubusercontent.com/17127080/37869920-eff4aec8-2fc1-11e8-9e53-ac3fd7f4feed.png)

Fixing this requires either a fix from Blizzard or to write a name colouring function to replace the one TRP hooks onto...
