### ISSUE TITLE
Colors/Names Bugged Out

### ISSUE THREAD

**Issue by Sinserrar** [Ellypse/Total-RP-3#110]
After updating to the latest version of TRP3 all of my character's names are rainbow colored no matter what I do. By that I mean if you took the name 'Billy' every letter is colored differently. There doesn't seem to be a way to revert back, either. Believe me, I've tried. I also tried disabling all addons aside from TRP3 with no luck. To be clear it's been working fine for me until this latest update, when my names all get hit with the technicolor stick.

**Comment by Ellypse** [comment]
You can disable the April fools’ joke in the tooltips settings ^^
