### ISSUE TITLE
World Map issues in Battle for Azeroth

### ISSUE THREAD

**Issue by Ellypse** [Ellypse/Total-RP-3#115]
This ticket will regroup and follow on the issues and the things that need to be updated to make the map functions work for Battle for Azeroth.

- [x] Use `C_Map.GetBestMapForUnit("player")` to check the player's current map and answer request.
- [x] But use `C_Map.GetCurrentMapID()` to get the map displayed in the UI to send request.
- [x] Use the new `C_Map.GetPlayerMapPosition(uiMapID, unit)` to get the player map coordinates **(Not yet implemented in game)**
- [ ] Use World Map Data Providers for the markers instead of anchoring them manually. This should make the system more compatible with other World Map mods.

**Comment by Ellypse** [comment]
The further emphasize the last point, here's a quote from the #wowuidev IRC channel
> 05:05:27 TheDanW: it is highly recommended that anything you add to the map is through the data provider api

**Comment by Ellypse** [comment]
Note: Current implementation of the data provider uses existing Blizzard frame levels for our own pins. We should be using `MapCanvasPinFrameLevelsManagerMixin:InsertFrameLevelAbove(frameLevelType, relativeFrameLevelType, optionalRange)` to create our own layer and have it placed at the right level.

**Comment by Ellypse** [comment]
With war mode in BfA, the player scan should send if the player sending the request is currently in war mode. When answering requests, we should check that the players are in the same mode. 
Check if this is true for major city or if we shouldn’t do this for those.

**Comment by Solanya** [comment]
This just in : Add an option to still show different war mode players pins, but greyed out.
