### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by TheDyna** [Ellypse/Total-RP-3#117]
### What steps will reproduce the problem?
Logging in
### What is the expected output? What do you see instead?
No TRP or Listener
### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
Not yet
### What version of Total RP 3 are you using?
1.3.4.1
### Was it working in a previous version? If yes, which was the last good one?
Yes, the one before this.
### Do you have an error log or screenshot of what happened?

Date: 2018-05-01 12:07:44
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\totalRP3\core\impl\ui_tools.lua line 483:
   attempt to index field 'Locale' (a nil value)
Debug:
   totalRP3\core\impl\ui_tools.lua:483: in main chunk
Locals:
_ = "totalRP3"
TRP3_API = <table> {
 formats = <table> {
 }
 utils = <table> {
 }
 Ellyb = <table> {
 }
 globals = <table> {
 }
 ui = <table> {
 }
 events = <table> {
 }
 Workarounds = <table> {
 }
 r = <table> {
 }
}
globals = <table> {
 addon_name_me = "Total RP 3"
 addon_name_short = "TRP3"
 clients = <table> {
 }
 player_class_loc = "Warrior"
 player_race_loc = "Goblin"
 addon_name = "Total RP 3"
 addon = <table> {
 }
 build = <function> defined @Interface\AddOns\totalRP3\core\impl\globals.lua:127
 PSYCHO_DEFAULT_RIGHT_COLOR = <table> {
 }
 PSYCHO_MAX_VALUE_V2 = 20
 empty = <table> {
 }
 player_character = <table> {
 }
 addon_name_extended = "TRP3: Extended"
 RELATIONS = <table> {
 }
 RELATIONS_ORDER = <table> {
 }
 is_trial_account = false
 PSYCHO_MAX_VALUE_V1 = 6
 DEBUG_MODE = false
 player_realm = "Wyrmrest Accord"
 icons = <table> {
 }
 version_display = "1.3.4.1"
 PSYCHO_DEFAULT_VALUE_V2 = 10
 player = "Sparklespazz"
 addon_id_length = 15
 PSYCHO_DEFAULT_VALUE_V1 = 3
 player_class_index = 1
 player_faction_loc = "Horde"
 PSYCHO_DEFAULT_LEFT_COLOR = <table> {
 }
 version = 45
}
loc = nil
floor = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
assert = <function> defined =[C]:-1
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:70
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 734
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 394
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 BOOKTYPE_PROFESSION = "professions"
 AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture {
 }
 VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture = VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 AudioOptionsVoicePanelMicrophoneVolumeThumb = AudioOptionsVoicePanelMicrophoneVolumeThumb {
 }
 PaperDollTitlesPaneButton12BgTop = PaperDollTitlesPaneButton12BgTop {
 }
 MANA = "Mana"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2346
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 943
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 ToggleEncounterJournal = <function> defined 
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  Altoholic, vr183
  AtlasLoot, vv8.07.13
  AtlasLootBurningCrusade, vv8.07.13
  AtlasLootCataclysm, vv8.07.13
  AtlasLootClassic, vv8.07.13
  AtlasLootLegion, vv8.07.13
  AtlasLootMistsofPandaria, vv8.07.13
  AtlasLootWarlordsofDraenor, vv8.07.13
  AtlasLootWrathoftheLichKing, vv8.07.13
  Auctionator, v4.0.19
  Babylonian, v5.1.DEV.332(/embedded)
  Clique, vv70300-1.0.0
  CloseUp, v7.3.003
  Configator, v5.1.DEV.431(/embedded)
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  DBMCore, v7.3.26
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Elephant, v3.7.5
  Gatherer, v7.3.1
  GHI, v2.1.25
  GHM, v
  HandyNotes, vv1.4.15
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLunarFestival, vv1.4.5
  Listener, v2.0.8
  SlideBar, v7.3.1 (<%codename%>)
  totalRP3, v1.3.3.2
  totalRP3Data, v
  BlizRuntimeLib_enUS v7.3.5.70300 <none>
  (ck=4e1)

### If your issue is related to profile data, please provide your data file.

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by TheDyna** [comment]
Loaded it up with no other addons, still got an error.

**Comment by Solanya** [comment]
Are you using a specific language ? I can't reproduce the issue.

**Comment by TheDyna** [comment]
Orcish, if that's what you mean.

**Comment by Solanya** [comment]
No I meant English or something else

**Comment by TheDyna** [comment]
English, yeah.

**Comment by TheDyna** [comment]
Okay, I completely shutdown battle.net and everything. It looks to be fixed.
