### ISSUE TITLE
TRP3 Lua error?

### ISSUE THREAD

**Issue by Adelric-115** [Ellypse/Total-RP-3#125]
Hello,

Today I updated my TRP3 to the latest version and logged into World of Warcraft with the following addons enabled:

TRP3
DBM
Elvui
Storylines

And to my surprise upon logging in I was confronted with a small window which described a Lua error, with a further 103 pages of related errors. The First Page's error identified the following:

"Message: Interface\AddOns\totalRP3\libs\Ellyb\Ellyb.lua:113: attempt to call method '_GetAddonVersions' (a nil value)
Time: 05/20/18 19:10:52
Count: 1
Stack: Interface\AddOns\totalRP3\libs\Ellyb\Ellyb.lua:113: attempt to call method '_GetAddonVersions' (a nil value)
[C]: in function `_GetAddonVersions'
Interface\AddOns\totalRP3\libs\Ellyb\Ellyb.lua:113: in function `_ImportInstances'
Interface\AddOns\totalRP3\libs\Ellyb\Ellyb.lua:127: in main chunk
Locals:"

If more information is required I'd be happy to provide, I'm not certain what has created this issue as it has only emerged today after using TRP3 without issue for several years.

**Comment by Solanya** [comment]
- Have you tried with only TRP3 enabled ?
- Do you have Storyline updated as well ? (They use the same library and there was some conflict when it was first added)

**Comment by Adelric-115** [comment]
Ah, It seems once I updated Storyline that did the trick thanks for the suggestion I didn't thank of that when first trouble-shooting the addon.
