### ISSUE TITLE
Chat error/no display of any kind.

### ISSUE THREAD

**Issue by Galafina** [Ellypse/Total-RP-3#126]
### What steps will reproduce the problem?
Opening the game/enabling the addon.
### What is the expected output? What do you see instead?
I expect to see it, instead of nothing.  I see nothing.
### What version of Total RP 3 are you using?
The latest, I checked five times.
### Was it working in a previous version? If yes, which was the last good one?
No.
### Do you have an error log or screenshot of what happened?
 Interface\AddOns\totalRP3\modules\flyaway\flyaway_patches.lua:89: attempt to index global 'TRP3_Register' (a nil value)
> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

### Please provide any additional information below.
I've tried uninstalling and reinstalling, logging in and out, exiting out completely and restarting, googling the error, pretty much everything I could think of, and nothing's worked or helped.

### If your issue is related to profile data, please provide your data file.

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Solanya** [comment]
Given the error message, the addon should work again if you roll back to the previous version (1.3.4.2) : https://wow.curseforge.com/projects/total-rp-3/files/2560555
If it was the first time you launched the addon, logging on a character with TRP3 1.3.4.2 and quitting the game *should* make it safe to update back to 1.3.4.3.

In any case I'll send a potential fix to Ellypse.

**Comment by Galafina** [comment]
I don't know how to install it from the zip file, do I place the folders in my WoW directory somewhere?
