### ISSUE TITLE
Problem with Cross-Realm

### ISSUE THREAD

**Issue by MagicalMoron** [Ellypse/Total-RP-3#128]
Not sure why, but when I grouped cross-realm with one of my friends, I was able to see their TRP3 info (they are on Wyrmrest Accord) but they could not see mine (I am obviously not on WA). Am I supposed to be able to see cross realm profile and there's a bug? I appreciate any response!

**Comment by Ellypse** [comment]
Please read the FAQ https://github.com/Ellypse/Total-RP-3/wiki/Frequently-Asked-Questions#does-total-rp-3-work-cross-realm-or-cross-faction

>## Does Total RP 3 work cross realm or cross faction?
>Due to the game limitations, Total RP 3's cross realm support is limited. You can fully use Total RP 3 with players from realms that are merged to yours (those are the realms that share the same channels in major cities. Players from those realms have their realm next to their names when they write in those channels. They usually share the same forum on Blizzard’s website too). Unfortunately, add-ons cannot exchange data with players in cross-realm zones (zones with a low population of players where servers are dynamically merged so it feels less deserted) or in groups created via the dungeon group finder or raid finder.
>
>Total RP 3 uses the standard SendAddonMessage() function to exchange data via the whispers channel (necessary for a one-to-one communication). This currently silently fails for the cases mentioned above. As soon as Blizzard makes it possible to send add-on messages via whispers in those cases, the add-on will be working as intended automatically without even needing an update.
>
>Add-ons cannot send messages to players of the other faction, so Total RP 3 cannot fetch the profile of a player of the other faction or send your profile to a player of the other faction. But, Total RP 3 caches profiles in the directory and will display the cached information if it can't update a profile. This means that if you play in both factions on your server, you will be able to see cached versions of profiles of players from the opposite faction if you met them previously.
