### ISSUE TITLE
Error during addon loading sequence:

### ISSUE THREAD

**Issue by DimsuumPanda** [Ellypse/Total-RP-3#133]
TRP3 is unable to load since server restart today.
The current version installed (using the same version when it was working previously) is 1.3.4.4 and the issue still persists with all other addons disabled.
![image](https://user-images.githubusercontent.com/40211195/41304077-bd625ad0-6e34-11e8-9648-907e2e544562.png)

**Comment by Ellypse** [comment]
Today’s hotfixes during the maintenance have broken something on Blizzard’s side. It has been reported to them by me and other addon developers. They will have to fix this on their side, there is nothing for us to do. No ETA.

**Comment by Solanya** [comment]
As a heads-up, you can just use the `/reload` command after logging in, and the addon will load properly as far as my tests go.

**Comment by DimsuumPanda** [comment]
Reloading did not work for me, but good to know it's on the Blizz end! Thanks. :)

**Comment by DimsuumPanda** [comment]
Reloading did not work for me, but good to know it's on the Blizz end! Thanks. :)
(Apologies never used github before.)
