### ISSUE TITLE
Issue with TRP's showing up

### ISSUE THREAD

**Issue by Annalyn154** [Ellypse/Total-RP-3#136]
### What steps will reproduce the problem?
Don't need steps to reproduce it, It just wont show anyones TRP, and they can't see mine

### What is the expected output? What do you see instead?
I expect that when I click on someone I can pull up their TRP, and it isn't pulling anything up.
### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes
### What version of Total RP 3 are you using?
Most Current, released on 6/12/18
### Was it working in a previous version? If yes, which was the last good one?
Yes, The past version
### Do you have an error log or screenshot of what happened?
No
> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

### If your issue is related to profile data, please provide your data file.

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Solanya** [comment]
Given the issues that came from the maintenance earlier, we don't have a reliable way of knowing if this is on Blizzard's end or ours. We're waiting for a realm restart to hopefully get things sorted out.

**Comment by Garrus818** [comment]
Any update on this? I'm having problems loading my friends TRPs :l

**Comment by Ellypse** [comment]
Nope. We’re waiting too.

**Comment by Solanya** [comment]
You can try to downgrade to 1.3.4.4 for now, issue doesn't seem to happen on that version as far as reports go.

**Comment by Annalyn154** [comment]
How do you downgrade without losing all of your data?

**Comment by dwergaz** [comment]
You shouldn't lose any data, I don't think. I went back to 1.3.4.4 last night with no issues. It was the same process as updating -- just download the old file, open up your AddOns folder, and drag to replace.

**Comment by Solanya** [comment]
Sorry for the lack of answer, version 1.3.5.2 was released earlier to fix the issue anyway, you should be able to download it through the Twitch app.

**Comment by Annalyn154** [comment]
Thank you, works amazing now!
