### ISSUE TITLE
Attempt to register unknown event "WORLD_MAP_UPDATE"

### ISSUE THREAD

**Issue by windpawzz** [Ellypse/Total-RP-3#168]
### What steps will reproduce the problem?
I've done nothing out of the ordinary. I logged in at around 03:00 and got the error as mentioned above.
(Argent Dawn Europe)

### What is the expected output? What do you see instead?
TRP should work normally, but it doesn't. Also quite noticeable is the fact WoW says it's out of date, despite it being the most recent version from july 21st. Is does this for MogIt and UnlimitedChatMessages as well.

### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yup! The exact same result. I even tried installing 1.4.2 and got the same error. I also did a clean install, with and without the Twitch client. Same result.

### What version of Total RP 3 are you using?
Was using 1.4.2 when the error occured and it persisted, even when I updated to 1.4.3

### Was it working in a previous version? If yes, which was the last good one?
1.4.2 worked for me a few days ago.

### Do you have an error log or screenshot of what happened?
https://imgur.com/a/TgXNP0r

> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

### Please provide any additional information below.
I've asked Tradechat if anyone else had the problem, and it seems I am the only one. I don't use any other addons at all and there's nothing out of the ordinary with my WoW client itself. I start it through the Battle.net app as always.

Here's the error written down:
[TRP3] The profile Argent Dawn - Wíllìams is loaded.
[TRP3] Error during addon loading sequence:
   Sequence ID: Globals.addon.OnEnable
   Sub-sequence ID: TRP3_API.events.fireEvent::WORKFLOW_ON_LOAD
   Error message: ...face\AddOns\totalRP3\libs|Ellb\Tools\GameEvents.lua:42:
   Attempt to register unknown event "WORLD_MAP_UPDATE"

### If your issue is related to profile data, please provide your data file.

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Ellypse** [comment]
![Image](https://i.imgur.com/AkRb3wv.jpg)
