### ISSUE TITLE
TRP3 profiles appear to no longer load through Bnet.

### ISSUE THREAD

**Issue by Katoriehooves** [Ellypse/Total-RP-3#174]
### What steps will reproduce the problem?
Try to load any TRP3 user's profile cross faction or realm, using any MSP addon.
### What is the expected output? What do you see instead?
Expected a profile. Got nothing.
### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes.
### What version of Total RP 3 are you using?
1.4.3
### Was it working in a previous version? If yes, which was the last good one?
Yes, it was working last week. Don't know which version of TRP it was.
### Do you have an error log or screenshot of what happened?
https://cdn.discordapp.com/attachments/265077101730725888/470901498008698890/screenie.png

Screenshot from friend's end trying to load mine.

### Please provide any additional information below.
Tested with TRP3, MRP, and XRP. All fail to load TRP3 data. MRP to MRP still works.

**Comment by Solanya** [comment]
LibMSP wasn't updated to v14 before 1.4.3 release.
