### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by elphabus** [Ellypse/Total-RP-3#181]
### What steps will reproduce the problem?
Adding an icon to the things you can see from a Character.

### What is the expected output? What do you see instead?
No specific race icon (allied races).

### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes.

### What version of Total RP 3 are you using?
1.4.3

### Was it working in a previous version? If yes, which was the last good one?
No, since Allied Races are fairly new.

### Do you have an error log or screenshot of what happened?

> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

### Please provide any additional information below.
This is not a big-ass game-breaking error, I just noticed some icons for allied races are missing. In my case, specifically the Lightforged Draenei Male/Female icons.

### If your issue is related to profile data, please provide your data file.

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Ellypse** [comment]
Allied races icons were added back in February.
https://github.com/Ellypse/Total-RP-3/commit/13a6e4c602d4d12413d56df006d83be4c74c3a1b#diff-328ccad879fe44c3928b15fbd0ac3081

**Comment by elphabus** [comment]
The icons I'm specifically looking for are race_lightforgeddraenei_male and race_voidelf_male but I can't seem to find them.

**Comment by Solanya** [comment]
Not sure what you're talking about, but those icon names don't exist in-game.

**Comment by Ellypse** [comment]
I cannot find these icons on WoWhead.
http://www.wowhead.com/icons/name:race_lightforgeddraenei_male
http://www.wowhead.com/icons/name:race_voidelf_male
Are you sure they exist with that name? Do you have a screenshot of what they look like?

**Comment by elphabus** [comment]
Oh. I'm sorry. I mean the icons that show up in the character creation screen, the 'faces', so to say. There's two per race, one male and one female.

**Comment by Ellypse** [comment]
Those are not real "icons" but parts of a bigger textures and are not compatible with the icons system for technical reasons. None of those are available, it's not just those two allied races.

**Comment by Ellypse** [comment]
For reference, this is what the texture looks like
![](https://github.com/Ellypse/wow-ui-textures/blob/live/Glues/CHARACTERCREATE/CharacterCreateIcons.PNG?raw=true)
