### ISSUE TITLE
Remove broadcast channel join delay and switch its position

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3#190]
As Blizzard added a way to switch channel positions, the workaround to wait before joining the broadcast channel isn't needed anymore. We can join the channel as soon as possible, then after the current delay, switch channel positions (using `SwapChatChannelByLocalID`) to put the broadcast channel at the bottom (preferably switching 1 by 1 until the bottom of the list instead of switching with the last channel, to keep the relative order of the other channels.)

**Comment by Ellypse** [comment]
The broadcast channel is already joined too early in 1.5.0-alpha1. This means we will need to do this within the scope of version 1.5.0.
