### ISSUE TITLE
Connected realms filter for Directory

### ISSUE THREAD

**Issue by Tuhljin** [Ellypse/Total-RP-3#192]
The "This realm only" checkbox on the character list of the Directory page filters the list so only characters of that realm are shown, but this is less useful on realms that are connected to others. You could even be in the same guild as a character but its profile wouldn't show up in the list.

I think that the filter should not remove profiles from connected realms, and perhaps it should be renamed to reflect this.

**Comment by Ellypse** [comment]
> Development note: use `GetAutoCompleteRealms()` to get list of connected realms.
