### ISSUE TITLE
Colour tag conversion for MSP not always working

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3#198]
When converting a TRP profile for MSP transfer, Markdown tags are converted into WoW-compatible codes ({col:rrggbb} into |cffrrggbb for instance). This conversion works in many cases but seems to fail on some occasions, and the Markdown codes are thus shown in plain text for other addons.

![image](https://user-images.githubusercontent.com/17127080/43857046-786739e4-9b4a-11e8-8384-41f5386444fe.png)

I was able to secure a profile causing incorrect conversion for later investigation : https://gist.github.com/Solanya/30364d1f5a72cdeb8bff76f9b0d99dc4

**Comment by Ellypse** [comment]
This is probably fixed by pull request #196 which makes sure all templates are parsed to convert Total RP 3 tags, not just template 1.
