### ISSUE TITLE
Check CVar from class colouring

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3#199]
**Is your feature request related to a problem? Please describe.**
`/console SET chatClassColorOverride "1"` disables class colours in the default chat frame, but this behaviour isn't followed by TRP's own color function.

**Describe the solution you'd like**
We should check chatClassColorOverride to know whether or not we should apply class colours.

**Comment by sylcai** [comment]
This is an extremely annoying bug. I get nausious from class colours in chat, update this QUICKLY please.

**Comment by sylcai** [comment]
I reverted back to 1.4.3 as it does not have the issues. :) But thank you. Sorry if I seemed... a bit... demanding. Apologies.
