### ISSUE TITLE
String of errors related to the same issue.

### ISSUE THREAD

**Issue by Zuuda** [Ellypse/Total-RP-3#200]
Every time I log in or reload I have this error. But it's actually a string of errors from many different addons, but they are all related to the same 30 and 37 line. I tried to comment those two lines out but then TRP3 stopped working.

Date: 2018-08-11 20:16:47
ID: 23
Error occured in: Global
Count: 1
Message: Error loading ..\AddOns\GarrisonMissionManager\+DEVEL.lua
Debug:
   totalRP3\libs\Ellyb\Ellyb.lua:37:
      totalRP3\libs\Ellyb\Ellyb.lua:30

Date: 2018-08-11 20:16:47
ID: 22
Error occured in: Global
Count: 3
Message: Error loading ..\AddOns\GarrisonMissionManager\+DEVEL.lua
Debug:
   totalRP3\libs\Ellyb\Ellyb.lua:37:
      totalRP3\libs\Ellyb\Ellyb.lua:30

Date: 2018-08-11 20:16:27
ID: 18
Error occured in: Global
Count: 3
Message: Error loading ..\AddOns\Tongues\Custom\customdialects.lua
Debug:
   totalRP3\libs\Ellyb\Ellyb.lua:37:
      totalRP3\libs\Ellyb\Ellyb.lua:30
Locals:
None

This goes on and on, but I stopped counting at 50. I've tried deleting TRP, the cache and the variables then reinstalling but no luck. With TRP disabled I get no errors.

**Comment by Ellypse** [comment]
Thank you for the report. Because of an issue in the current version of Total RP 3 it is reported as the cause of these issues incorrectly. These are issues with GarrisonMissionManager and Tongues. 

I will fix Total RP 3 so it is no longer incorrectly reported as the source of the error.

**Comment by Zuuda** [comment]
Good to know! I've deleted both Tongues and GMM since I'm using neither and the errors did stop right away. Even just Tongues was enough to get the errors back so fie to it.

**Comment by Zuuda** [comment]
I won't dispute that it is harmless since nothing really seems to be happening (I just dislike having LUA errors since I come from a background of bad FPS in other cases coming from addons), but disabling TRP and reloading a few times gave me no errors where enabling it again and reloading had the multiple errors come back. I have no clue what this means in this context.
