### ISSUE TITLE
TRP DropDownMenu Error.

### ISSUE THREAD

**Issue by Hobskins** [Ellypse/Total-RP-3#214]
Date: 2018-09-02 08:58:32
ID: 1
Error occured in: Global
Count: 7
Message: Deferred XML Node object named MSA_DropDownMenuButtonTemplate already exists

FrameXML Logs:

9/2 08:58:29.868  Loading add-on totalRP3
9/2 08:58:29.868  ** Loading table of contents Interface\AddOns\totalRP3\totalRP3.toc
9/2 08:58:29.868  ++ Loading file Interface\AddOns\totalRP3\totalRP3.xml
9/2 08:58:29.868  ++ Loading file Interface\AddOns\totalRP3\libs\libs.xml
9/2 08:58:29.868  ++ Loading file Interface\AddOns\totalRP3\libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.xml
9/2 08:58:29.868  ++ Loading file Interface\AddOns\totalRP3\libs\MSA-DropDownMenu-1.0\MSA-DropDownMenuTemplates.xml
9/2 08:58:29.868  Deferred XML Node object named MSA_DropDownMenuButtonTemplate already exists
9/2 08:58:29.868  Deferred XML Node object named MSA_DropDownListTemplate already exists
9/2 08:58:29.868  Deferred XML Node object named MSA_DropDownMenuTemplate already exists

**Comment by Ellypse** [comment]
This issue is fixed in version 1.4.5, currently in beta.
