### ISSUE TITLE
TRP3 messing with Action Bars

### ISSUE THREAD

**Issue by reportabug** [Ellypse/Total-RP-3#216]
**Describe the bug**
I'm having a problem where randomly my buttons will become non-interactable. I can not click them, or use any key-binds to make them work. Eventually they will decide to work again, but by then usually another set of buttons would become non-interactable. I was even having an issue with hovering over debuffs/buffs; no tooltip would show on the last few or first few debuffs/buffs displayed at random times. Reloading, logging out, completely restarting the game, seriously nothing would fix this issue; they would just come and go as they please. So I went into all my addons and disabled everything, turning on each one by one. I found out that it was TRP3 causing this issue much to my dismay, every other addon was running smoothly. I reinstalled it multiple times hoping for the issue to go away, but so far the issue is still happening. For now I have TRP3 disabled, but I really hope that there is a way to fix this so I can continue to have amazing experiences with this addon. 

**To Reproduce**
Steps to reproduce the behaviour:
I don't know if there are certain things that trigger this behavior. Usually just having TRP3 enabled would result in the issue. I'd re-enable it and immediately after reload some buttons would be non-interactable.

**Screenshots or error message**
I downloaded Bugsack to see if any bugs were reported, but it did not show any errors. 
 
**Version of the add-on:**
Total RP 3 1.4.4

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Comment by Solanya** [comment]
Try downloading the latest version (1.4.6) to see if the issue is still there. As far as I'm aware, Total RP 3 doesn't interact with action bars, so this shouldn't happen. 🤔

**Comment by Ellypse** [comment]
Cannot reproduce this issue / not enough information provided.
