### ISSUE TITLE
Music pieces missing.

### ISSUE THREAD

**Issue by Cakestuff** [Ellypse/Total-RP-3#217]
**Describe the bug**
There seem to be several music pieces missing with the new expansion, when clicking on said pieces the music chosen doesn't play as the game seem incapable of finding the path to that music piece in particular. So far the pieces affected seem to be:
mus_80_kultiran_tavern_a
mus_80_kultiran_tavern_b
mus_80_kultiran_tavern_h
mus_80_pointofimpact_a
mus_80_pointofimpact_b
mus_80_pointofimpact_c
mus_80_pointofimpact_d
mus_80_pointofimpact_h

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to about
2. Click on Edit
3. Click on Character Theme
4. Scroll down to any of the music pieces mentioned above. I.E mus_80_kultiran_tavern_a
5. Note that the music chosen doesn't play and so instead the game keeps playing whatever was playing in the background to begin with.

**Expected behaviour**
I expected the chosen character theme to play over the background music, but if the path to said music is wrong that will not happen.

**Version of the add-on:**
Total RP 3 1.4.6

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Additional context**
There might be other music missing but those are the ones found to be unable to play for whatever reason.

**Comment by Solanya** [comment]
We don't have a way to get a reliable music list other than to rely on dataminers who already did the job. I've indeed seen some of the musics in the list not playing, at best we might be able to remove them from the list but that means checking each of the hundreds of new musics from 8.0. Not sure it's worth it.

**Comment by Cakestuff** [comment]
Heya, Could this entire list help in any way shape or form?
https://www.wowhead.com/news=285042/battle-for-azeroth-music
I know you already closed the thread but I hope it helps regardless.

Have a lovely day. And Thanks.

**Comment by Solanya** [comment]
It doesn't, Wowhead lists the music filenames which are different from the filepaths required to have the background music automatically shut up (instead of playing the file over the background music).

**Comment by Wazzupiddy** [comment]
Damn...I was really hoping to give my character the Kul Tiran tavern theme...such a good soundtrack >.<
