### ISSUE TITLE
Beta build conflicts with Details

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3#228]
https://cdn.discordapp.com/attachments/265483259994046464/503686943167479837/unknown.png

It seems for some reason that `FCF_GetCurrentChatFrame` returns nil when Details is loaded, which bugs out `ToggleChatChannel`. I've tried to quickly investigate the issue but couldn't find the cause for this.
Simple workaround right now would be to check that we're not getting nil on the FCF function.

Should this be reported to the Details dev ?

**Comment by KyBelle01** [comment]
Date: 2019-06-13 15:01:29
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\totalRP3\libs\LibMSP\Chomp\Internal.lua line 378:
   table index is nil
Debug:
   ...rface\AddOns\totalRP3\libs\LibMSP\Chomp\Internal.lua:378:
      ...rface\AddOns\totalRP3\libs\LibMSP\Chomp\Internal.lua:376
   [C]: SendAddonMessage()
   ...erface\AddOns\DugisGuideViewerZ\DugisGuideViewer.lua:7616: SendDataToServer()
   ...erface\AddOns\DugisGuideViewerZ\DugisGuideViewer.lua:1078:
      ...erface\AddOns\DugisGuideViewerZ\DugisGuideViewer.lua:1073
Locals:
prefix = "dugis"
text = "CLIENT_ONLINE:nil"
kind = "WHISPER"
target = nil
(*temporary) = <table> {
 Annewynn = 4751.449000
}
(*temporary) = 4751.449000
(*temporary) = 0.076000
(*temporary) = 3
(*temporary) = 2.459981
(*temporary) = 0.196037
(*temporary) = "table index is nil"
Internal = <unnamed> {
 0 = <userdata>
 OnTick = <function> defined @Interface\AddOns\totalRP3\libs\LibMSP\Chomp\Internal.lua:344
 BURST = 8192
 BITS = <table> {
 }
 lastByteUpdate = 4746.373000
 SameRealm = <table> {
 }
 Enqueue = <function> defined @Interface\AddOns\totalRP3\libs\LibMSP\Chomp\Internal.lua:313
 MEDIUM = <table> {
 }
 VERSION = 8
 ErrorCallbacks = <table> {
 }
 isReady = true
 DecodeQuotedPrintable = <function> defined @Interface\AddOns\totalRP3\libs\LibMSP\Chomp\StringManip.lua:317
 isSending = false
 bytes = 7855
 Serialize = <table> {
 }
 StartQueue = <function> defined @Interface\AddOns\totalRP3\libs\LibMSP\Chomp\Internal.lua:337
 KNOWN_BITS = 2073
 RunQueue = <function> defined @Interface\AddOns\totalRP3\libs\LibMSP\Chomp\Internal.lua:251
 ChompAPI = <table> {
 }
 EncodeQuotedPrintable = <function> defined @Interface\AddOns\totalRP3\libs\LibMSP\Chomp\StringManip.lua:191
 LOW = <table> {
 }
 BPS = 2048
 UpdateBytes = <function> defined @Interface\AddOns\totalRP3\libs\LibMSP\Chomp\Internal.lua:296
 HIGH = <table> {
 }
 Filter = <table> {
 }
 Prefixes = <table> {
 }
}
OVERHEAD = 27

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AccountWideRaidProfiles, v1.1.1
  Armory, vv15.4.1
  ArmoryGuildBank, vv15.4.1
  BlizzMove, vv1.8
  BuyEmAll, v3.5.3
  CanIMogIt, v8.1.5v1.14
  Castbars, v
  Details, v
  DetailsCombined, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DugisGuideViewerZ, v8.731
  kSellGreyNRepair, v1.4
  Postal, vv3.6.0
  RaiderIO, v8.1.0 (v201906130636)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  RaidFrameIndicators, v1.0.5b
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  toomanyaddons, vr47
  totalRP3, v1.6.0
  totalRP3Data, v
  tRP3RDotIO, v1.0.4
  WIM, v606
  WIMElvUISkin, v80000.01-Release
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=32e)
