### ISSUE TITLE
TRP3 "Titles" in Kui Name plates not working after recent update.

### ISSUE THREAD

**Issue by holycinders** [Ellypse/Total-RP-3#232]
**Describe the bug**
After updating to the recent version of TRP3, Kui nameplates and TRP does not display custom titles even with the setting checked for custom titles.

**To Reproduce**
Steps to reproduce the behaviour:
I have all nameplates enabled but it still only displays the character name instead of the custom title name. :(

**Expected behaviour**
To allow me to see custom titles via kui name plates and TRP3, as it used to before the update.
**Screenshots or error message**
https://i.imgur.com/SbREYEg.jpg
> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

**Version of the add-on:**
Total RP 3 1.5.0

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Additional context**
I did not have this problem until the update.

**If your issue is related to profile data, please provide your data file.**

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Solanya** [comment]
There is a new version (1.4.1) currently in beta to fix issues that came from changes to the main Kui Nameplates addon.
If you're using the Twitch App, you can right-click on the Total RP 3: KuiNameplates module and select Release Type > Beta to be able to download it. If you want to install it manually, here's the link : https://wow.curseforge.com/projects/total-rp-3-kuinameplates-module/files/2630744

**Comment by holycinders** [comment]
> There is a new version of the Total RP 3: KuiNameplates module (1.4.1) currently in beta to fix issues that came from changes to the main Kui Nameplates addon.
> 
> If you're using the Twitch App, you can right-click on the Total RP 3: KuiNameplates module and select Release Type > Beta to be able to download it. If you want to install it manually, here's the link : https://wow.curseforge.com/projects/total-rp-3-kuinameplates-module/files/2630744

I shall have to make sure I update it then and see if it helps. I'll report back after I do!
