### ISSUE TITLE
xtensionxtooltip2 need a password

### ISSUE THREAD

**Issue by IvanVilla** [Ellypse/Total-RP-3#234]
**Describe the bug**
We have also added additionnal protections and monitoring against people trying to prevent you from joining the broadcast channel xtensionxtooltip2 by adding a password to the channel.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to use the addon map feature after installing.

**Expected behaviour**
What is the password for xtensionxtooltip2?

**Screenshots or error message**
> Not necesary

**Version of the add-on:**
Total RP 3 1.5.0

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Additional context**
Not necessary

**If your issue is related to profile data, please provide your data file.**
Every profile

**Comment by IvanVilla** [comment]
I have just try the addon in Eu-Los Errantes and the channel have a password, but if I try in Argent Dawn, the addon doesn't need one.
I think somebody stole the channel in my realm.

**Comment by Solanya** [comment]
The channel isn't supposed to have a password. There is nothing we can do if someone decides to add one, whoever currently holds the leadership of that channel needs to remove the password.

There should have been a popup message when you logged in telling you the channel was locked by a password and who currently holds the leadership of that channel.

**Comment by Ellypse** [comment]
This is normal game behavior that we cannot fix on our side, unfortunately. The password will eventually disappear, during a weekly reset at the later.

**Comment by IvanVilla** [comment]
Thank you!
