### ISSUE TITLE
Trp3 performing illegal blizzard ui function

### ISSUE THREAD

**Issue by bsp3978** [Ellypse/Total-RP-3#240]
**Describe the bug**
A clear and concise description of what the bug is. illegal trp3 action against blizzard ui

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...' map
2. Click on '....' hit m on keyboard

**Expected behaviour**

**Screenshots or error message**
> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.  https://i.imgur.com/I0Vfw8r.jpg

**Version of the add-on:**
Total RP 3 1.5.0

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes/No no

**Additional context**

**If your issue is related to profile data, please provide your data file.**

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Solanya** [comment]
Try disabling every other addon and see if the issue still happens. If not, try narrowing down which addon causes the issue.

**Comment by bsp3978** [comment]
it is only on trp3 with all other addons completely disable and a reload of
the ui bug grabbers said it has to due with the clear function blizzard's
ui uses

**Comment by Ellypse** [comment]
This is most likely due to a known issue in Blizzard's code with drop-down menus creating "taint" which can cause some add-on actions to be blocked when executed during combat.

This issue has been fixed on 8.1 PTR on Blizzard's end.
