### ISSUE TITLE
TRP export parser?

### ISSUE THREAD

**Issue by proudmane** [Ellypse/Total-RP-3#246]
Hi!

I'm wondering if there exists or could exist in the future a parser tool to convert a TRP export string into another format such as JSON, YAML or another markup language that can be used to instantiate an object containing the information of the profile outside of the context of the LUA wow engine, specifically Ruby.

If there is nothing like it, is there documentation on exactly how the export strings are formatted so that one could create a tool to convert the strings to JSON?

**Comment by Ellypse** [comment]
Hello.

When exporting a profile from Total RP 3, we serialize a table that contains the add-on version, the ID of the profile and the actual content of the profile.

```lua
{
	[1] = Globals.version,
	[2] = profileID,
	[3] = profile
}
```

The serializer used is AceSerializer-3.0 ([documentation here](https://www.wowace.com/projects/ace3/pages/api/ace-serializer-3-0)). I don't know if there exists a tool to transform serials obtained from AceSerializer into JSON objects or other formats. I don't have any plan to create such tool as I will have no use for it.

The website [wago.io](http://wago.io) does support importing AceSerialized tables so it probably has some way of reading it. You can find the project on GitHub [here](https://github.com/oratory/wago.io).

Please note that the serialized exports are considered a private feature of Total RP 3 and not a public API, and as such are subject to breaking changes. I actually have on my todo list to encode them to base64 in a near future to prevent issues when people copy-paste them into word editors that change characters like quotes.

**Comment by proudmane** [comment]
got around to this after a few years i have something semi working for a C# TRP parser: https://github.com/proudmane/TRPBin/blob/master/TRPBin/Services/TestLuaService.cs#L16

thanks for the excellent documentation on the Wiki!
