### ISSUE TITLE
Total RP 3 is up to date, but won't show in game.

### ISSUE THREAD

**Issue by hanafrufru** [Ellypse/Total-RP-3#258]
**Describe the bug**

Hi, I've used TRP3 in the past on my laptop, but just got a new desktop computer and finally got WoW up and running. Downloaded Twitch to get my addons, all of which, except for TRP3 are up to date and run fine in game. When I log in to my account, and I'm on the character list, the game states that one of my addons is out date, and will interfere with interface and gameplay, yadda yadda. I'm having issues figuring out where the problem lies, as the TRP3 addon is up to date, and I've tried reinstalling and restarting both the addon and game several times. Still in game is stays saying out of date, while in the Twitch app, everything is up to date. I've tried searching google, your FAQ, and trouble shooting page, but have not found a way to fix this or come across anyone else who has experienced this. Any help would be appreciated! 

**Screenshots or error message**

The message that appears once logging on
![screenshot 1](https://user-images.githubusercontent.com/45862238/49975016-e8c7d900-ff09-11e8-8fe6-03dcbb311dda.png)

The message that appears after clicking "Disable addons"
![screenshot 2](https://user-images.githubusercontent.com/45862238/49975029-ed8c8d00-ff09-11e8-92ad-134157ee476a.png)

**Version of the add-on:**
Total RP 3 1.5.2

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Comment by Solanya** [comment]
Ignore the message, the fault is on Blizzard. They forgot to update the interface version number and are yet to fix it 2 days later.
