### ISSUE TITLE
TRP3 version not updating?

### ISSUE THREAD

**Issue by UndsunsRPer** [Ellypse/Total-RP-3#260]
I can't figure out why, but for some reason WoW will not recognize the updated version of TRP3.  I've been using TRP3 since v1.2.x, and never had this issue before.  I was running v1.4.6, and just updated to v1.5.2 this morning.  After updating the files in my Addons folder I logged in, (I had the 'load out of date addons' clicked off'), and TRP3 didn't load upon entering the game.  I logged out to my character selection screen, opened the addons window, and sure enough it read TRP3 as being out of date.  I logged out of the game and tried extracting v1.5.2 to my WoW addons folder again.  Still no joy.  I logged out, deleted TRP3+TRP3Data from my WoW Addons folder.  Then I deleted the Zip v1.4.6 file from my C:/... Downloads folder, so only the v1.5.2 file was left.  Emptied the Recycle bin and restarted my computer, figuring I'd have to re-do all my character profiles now.  On restarting, I extracted the v1.5.2 files into my WoW Addons folder, then started up the game.  No word of a lie, it STILL reads as v1.4.6 upon entering the game, all my character profiles were intact, and when I opened TRP3 in game, even TRP3 gave me the pop-up window to tell me an updated version, v1.5.2, was available. 
I have searched my C:/ drive, and dug through my WoW folders..... where is this info for v1.4.6 buried in and still coming from?

If this matters:  I'm not currently using my regular pay-to-play account, I'm just using a free Trial Account.  Also, I didn't try downloading the TRP3 extended version, only the regular TRP3 version.

**Comment by Solanya** [comment]
The path to install addons changed with patch 8.1, it's now `World of Warcraft\_retail_\Interface\AddOns`. Make sure you're installing there and not in the old folder.

**Comment by UndsunsRPer** [comment]
I thought that  \_retail_\ folder looked new.  Yes, that was the issue.  Thanks Solanya.
