### ISSUE TITLE
Can't type while in druid animal forms

### ISSUE THREAD

**Issue by Karvath** [Ellypse/Total-RP-3#275]
When I play as a druid, I cannot type anything into chat whatsoever when in an animal form. Out of the form, I can do it with no problem.

I've tried disabling all other addons, but the only one that seems to affect it is the TRP3 addon.

All are up to date, and I have tried re-loading my game several times, so I'm not sure what I can do to fix this

I've asked around, and it doesn't seem to be a problem for anyone else.

**Comment by Solanya** [comment]
I cannot indeed reproduce the issue.

Can you enable Lua errors by typing the command `/console scriptErrors 1` (if the game prompts you about it, accept and type it again) then try to speak while in animal form and share the Lua error you get ?

**Comment by Karvath** [comment]
I'm not very good with bugs and such, and I'm not quite sure which error message to send as I have six in total, so here they are one by one:
(1)
Message: Couldn't open Interface\AddOns\Tongues\-----------------------------------------------------------
Time: Fri Mar 15 14:19:47 2019
Count: 3

(2)
Message: Error loading Interface\AddOns\Tongues\Custom\customfilters.lua
Time: Fri Mar 15 14:19:47 2019
Count: 3

(3)
Message: Error loading Interface\AddOns\Tongues\Custom\customaffects.lua
Time: Fri Mar 15 14:19:47 2019
Count: 3

(4)
Message: Error loading Interface\AddOns\Tongues\Core\phonetics.lua
Time: Fri Mar 15 14:19:47 2019
Count: 3

(5)
Message: Error loading Interface\AddOns\Tongues\Custom\customlanguages.lua
Time: Fri Mar 15 14:19:47 2019
Count: 3

(6)
Message: Error loading Interface\AddOns\Tongues\Custom\customdialects.lua
Time: Fri Mar 15 14:19:47 2019
Count: 3

**Comment by Solanya** [comment]
None of those errors are related to TRP3, they're referring to Tongues.
Disable all of your addons except TRP3, try to type while in druid form, and see if you get another error.
