### ISSUE TITLE
Not sure it's considered a 'bug' but the 'interact/talk/inspect/ etc bar isnt showing

### ISSUE THREAD

**Issue by ShariAdune** [Ellypse/Total-RP-3#289]
**Describe the bug**
Just got the extended version yesterday.  Seems I am missing the added tooltip thing that has the options to talk/inspect etc NPCs and such.  Didn't know I was missing anything until I started watching tutorial videos and they kept using that bar and I,..... didn't have it.

I found this out when at the same step in a tutorial, they had the tooltip, yet I did not.

**Expected behavior**
I'd like to figure out what's going on that it's not coming up... 

**Version of the add-on:**
Total RP 3 1.5.4 (build 64)

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes tried that.

PS: Unrelated: But 'behavior' in your form here is spelt wrong.. there is no u in it. ;)

**Comment by Solanya** [comment]
Issue for Extended and not TRP3. You need an active campaign and an NPC targeted to see the actions, though this is something we're looking to improve : 
https://github.com/Ellypse/Total-RP-3-Extended/issues/6

PS : British English isn't wrong spelling.
