### ISSUE TITLE
Addon broken as of April first (not the april fools prank)

### ISSUE THREAD

**Issue by Gatheringofravens** [Ellypse/Total-RP-3#291]
Problem: April fools seems to have caused some serious issues.

Mousing over characters does not display the tooltips properly, additionally errors are thrown. 

Yes I did check if unchecking "Enable April Fool's Joke" in the tooltip section changed anything after a reload. It did not. 

See below example of error thrown (removed character name for privacy of that random individual, however the name is the same as the moused over character and I get plenty of them). Additionally the tooltips seem to bleed into each other at times, with multiple names and other text appearing on one tooltip.

I do not know if this is a blizzard April Fools of some sort but it only started happening after midnight rolled around.

RP IO score is quite funny though, I quite enjoyed it. And although I'm sure there are no plans to implement it I do wonder at the idea being taken seriously by some. It is an interesting concept although an imperfect one I suppose given not everyone tends to write out verbose profiles and one should never judge a book or role-player by a machine score.

Error follows(6th line I removed the character name and realm and replaced them with the <text>, it's the same for all moused over characters and not important):

Date: 2019-04-01 00:51:10
ID: 6
Error occured in: Global
Count: 4
Message: ...talRP3\modules\register\characters\register_main.lua line 351:
   Unknown character: <CHARACTERNAME>-<REALM>
Debug:
   [C]: ?
   ...talRP3\modules\register\characters\register_main.lua:351:
      ...talRP3\modules\register\characters\register_main.lua:350
   ...\totalRP3\modules\register\main\register_tooltip.lua:649:
      ...\totalRP3\modules\register\main\register_tooltip.lua:409
   ...\totalRP3\modules\register\main\register_tooltip.lua:1057:
      ...\totalRP3\modules\register\main\register_tooltip.lua:1010
   ...\totalRP3\modules\register\main\register_tooltip.lua:1161: callback()
   ...ddOns\totalRP3\libs\Ellyb\Tools\EventsDispatcher.lua:74: TriggerEvent()
   totalRP3\core\impl\events.lua:123: fireEvent()
   ...\totalRP3\modules\register\main\register_tooltip.lua:1148: callback()
   ...ddOns\totalRP3\libs\Ellyb\Tools\EventsDispatcher.lua:74: TriggerEvent()
   ...face\AddOns\totalRP3\libs\Ellyb\Tools\GameEvents.lua:43:
      ...face\AddOns\totalRP3\libs\Ellyb\Tools\GameEvents.lua:41
Locals:
(*temporary) = false
(*temporary) = "Unknown character: Milakee-MoonGuard"

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  ACP, vr259 
  ActionBarProfiles, v8.0.1
  AdvancedInterfaceOptions, v1.2.4
  AllTheThings, v1.8.6c
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  auccheapsearcher, v20190305
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucScanData, v8.1.6229 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.7
  Bartender4, v4.8.1
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  CaerdonWardrobe, vv2.2.3
  CanIMogIt, v8.1.5v1.14
  Cromulent, v80000-2
  CurrencyTracker, v1.4
  DBMCore, v8.1.11-30-g918620059
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  EmoteSplitter, v1.5.2
  FlashTaskBar, v
  GTFO, v4.46.17
  Informant, v8.1.6246 (SwimmingSeadragon)
  Mapster, v1.8.2
  MikScrollingBattleText, v5.7.149
  Misspelled, v1.7.2
  MogIt, v3.9.0
  MogItArtifact, v3.9.0
  MogItOneHanded, v3.9.0
  MogItOther, v3.9.0
  MogItPlate, v3.9.0
  MogItRanged, v3.9.0
  MogItTwoHanded, v3.9.0
  OmniCC, v8.0.0
  Postal, vv3.6.0
  Prat30, vr1189      
  Prat30Libraries, v
  RangeDisplay, vv4.8.2
  Recount, vv8.0.1a
  SharedMedia, v3.1.0-193
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  SPTimers, v3.13.1
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TidyPlates, v6.19.3
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TokenSplainer, vr02
  TomTom, vv80100-1.0.1
  totalRP3, v1.5.4
  totalRP3Data, v
  totalRP3Extended, v1.3.1
  totalRP3ExtendedImpExport, v1.3.1
  totalRP3ExtendedTools, v1.3.1
  TransmogTokens, v1.4.1
  VuhDo, v3.100
  VuhDoOptions, v3.100
  WIM, v595
  XLoot, v8.1-1
  XLootFrame, v8.1-1
  XLootGroup, v8.1-1
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=926)

**Comment by Solanya** [comment]
There was an oversight and the actual setting to disable is "RP.IO" in the Register settings.

**Comment by Gatheringofravens** [comment]
Unticking that option seems to resolve it. Cheers.
