### ISSUE TITLE
Can't access trp on alts

### ISSUE THREAD

**Issue by Needanameaea** [Ellypse/Total-RP-3#296]
**Describe the bug**
I login to an alternate character (alt) but trp is no where to be found. I can't view my profile, or anyone else. When I login to another character, that profile is there, and I'm able to view other players trp profiles. I need trp to work properly on ALL my characters, including the ones I've already made profiles for.

**Version of the add-on:**
Current.

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Comment by Meorawr** [comment]
![image](https://user-images.githubusercontent.com/287102/57420177-4aad1600-71fe-11e9-8748-f47f5fc5d130.png)

If you open the AddOns list on the character selection menu, and select the character in question from the dropdown does TRP show as actually being enabled with a *golden* checkbox (not silver)?

**Comment by Needanameaea** [comment]
This was it. I'm not sure why it was unchecked on a single alt, but thank you!
