### ISSUE TITLE
Pet profiles updating issues

### ISSUE THREAD

**Issue by Ellypse** [Ellypse/Total-RP-3#30]
> Solanya:
>This was tested on version 1.2.11.1 but got similar answers from a 1.2.9.1 user, so it might not be related to the latest update.
>At first glances on pet profiles seem not to update properly, although I can't pinpoint what happens. It might update them only on the first profile request, but I didn't have time to do a lot of tests.
>Here's what I got :
>- At first meeting of the pet, the profile was requested and loaded the first glance (it actually never requested one of the profiles for some reason, despite trying to update it or change it, not sure what was up with that)
>- Updating the pet icon, name or title was correctly updated on the other account.
>- Updating or adding pet first glances wasn't updated on the other account.
>- Deleting the profile in the register to request it again gives the right version.

**Comment by Ellypse** [comment]
Fixes is on bug_fix/companions_AFG_update but needs testing

**Comment by Solanya** [comment]
From the tests I did, pet profiles are updating properly when first glances are modified/enabled/disabled.
