### ISSUE TITLE
Suggestion: Use companion name (color, icon) in npc speeches

### ISSUE THREAD

**Issue by Ellypse** [Ellypse/Total-RP-3#40]
>Quote from @Kruithne via Twitter:
>“It would be cool if we could emote using pets/mounts. For example, I have a pet called Cat in my TRP. If I used /e Cat| scratches his backside. it would format properly in chat, showing his name colour/icon for people with that enabled.”

Check for companion bindings for the sender of the message.

**Comment by Solanya** [comment]
Update on tonight's efforts : 
- For say/yell/whispers, it was done without any issue.
![image](https://user-images.githubusercontent.com/17127080/35124150-536bb2da-fca5-11e7-9aec-8246f53a8d4c.png)
- For emotes, it's more complicated. Nothing indicates that your emote starts with a name, or separates that name from the rest of the emote. Random idea I used to test was to require an asterisk right after the name. _/e | Cat* scratches._ This also allowed me to add Lora's modification for 's and ,
![image](https://user-images.githubusercontent.com/17127080/35124438-64720e20-fca6-11e7-92f8-7ab882083c4f.png)
It's not consistent with the other talk types though. Should they all request an asterisk (or other symbol), should I bruteforce every known pet profile to see if one match the start of the emote (that sounds bad), or do you have another idea ?
