### ISSUE TITLE
Long lines without spacing break profile viewing

### ISSUE THREAD

**Issue by Ellypse** [Ellypse/Total-RP-3#7]
## BorBlasthammer created this issue Aug 30, 2015
The TRP3 Register About Panel fails to display complete descriptions, histories, or other multi-line text if those strings contain lines of too great a length (variable, but around 60 characters) which are not broken by spaces or other characters the UI considers equivalent to spaces (i.e., dashes).
This can be fixed by setting nonspacewrap="true" in the XML definitions, such as on lines 439, 465, and 491 of modules/register/characters/register_ui_about.xml for the third About template variant. There are likely other places that would need the same change, and this shouldn't break the normal display, as FontStrings still prefer to wrap at space characters even when nonspacewrap="true", only wrapping at non-space characters when no spaces are present.
Test case:
Create a profile with template 3 containing the following description text:
`============================================IC=================================================`

This text will be hidden off the edge of the display, truncated by ... instead of wrapped for normal display.
Viewing the profile from any copy of TRP3 will demonstrate the issue, failing to display any text beyond roughly the 60th character of the first line. It will also fail to display properly in the preview section of the editor (at less than the 60th character, due to the shorter frame width), and the same issue can also be seen with template 2.
The suggested fix can be tested in-game by using /fstack to determine the name of the FontString being viewed and running FontStringName:SetNonSpaceWrap(true) to see the difference immediately.

**Comment by Meorawr** [comment]
This was actually legitimately fixed in 1.5.4 (#279). The originally referenced commit disappeared into the ether at some point.
