### ISSUE TITLE
Add modifiers to the roll command

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3#75]
"Some form of modifier syntax (+ and -) would be super handy for events so people can bake their stat modifiers into the rolls rather than having to do the math afterwards and then inform everyone they're roll is actually X not Y."
"/trp3 roll 1d20+10 as an ideal syntax"

(Also check if the target is a player when sending the dice roll)

**Comment by Ellypse** [comment]
Check the target’s faction also
