### ISSUE TITLE
TRP3's 'open' slash command not respecting Bizzard unit identifiers

### ISSUE THREAD

**Issue by Gatheringofravens** [Ellypse/Total-RP-3#84]
### What steps will reproduce the problem?
1. Create a macro with the following "/trp3 open mouseover"
2. Use the macro while moused over another player with trp3.

### What is the expected output? What do you see instead?
Expected output should be the profile of the moused over person opening.

Instead no profile opens and the message: "No player named 'Mouseover-[server]" is currently playing"

### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
ElvUI is not enabled. No other RP profile addons are enabled. 

### What version of Total RP 3 are you using?
1.3.1-beta-1 (latest)

### Was it working in a previous version? If yes, which was the last good one?
Unknown.

### Please provide any additional information below.

It also fails when used with "target" and "focus" and I'd expect all other Blizzard supplied unit identifiers.

The similar "show" command with MRP and XRP ex. "/xrp show mouseover" works just fine.

Instead of passing and trying to get data for the literal names "mouseover" and "target" may I suggest using Blizzard's mechanism to resolve them to the referred to units? 

I will note in XRP calling /xrp show mouseover shows the mouseover only when a unit is being moused over (and only when that unit is a player). So doing /xrp show mouseover while not moused over any character tries to pull up the profile for the name mouseover. 

I think this behavior is preferable to TRP3's current behavior and would ask that it be changed to respect "mouseover" and "target" when they return as having a mouseover or target and falling back to the literal name if the respective unit ID doesn't exist because there is no target or mouseover at the time.

I'm not sure how many people have use cases like mine but I'll lay it out anyways:

I tend to spend time in the city looking over profiles. To make this task easier I had when using XRP a macro which I bound to my mouse-button 7, so I just mouse over the character, tap the button on the side of my mouse and their profile opens. It saves me some clicks and I know a few other people who use similar macros. I may be doing other things at the same time as well and more than once before having this macro I'd targeted someone with the intent of looking at an interesting profile and then been distracted by something else, only being able to return to click the button a minute later by which time they'd zoned or gone out of targeting distance and I could no longer remember their character name or obviously click the button to display the profile.

It's not much of a reason I know but I'd argue there are very few characters with the literal name "target" or "mouseover" and fewer still on RP servers (where such names are technically a violation of RP realm name rules) and with my proposed solution someone can still get such a person's profile when not in proximity by clearing their target or moving their cursor off players. All while respecting expected behavior in things like macros. 

I'll be honest. I'm trying TRP3 again for the first time in around a year, last time one of the things that put me off was lack of an "open" command which made browsing more painful for someone like me who preferred to look over tooltips rather than use the directory, at least while around lots of people. I see this was actually a very recent addition and I want to applaud that while requesting this improvement. 

This is a rather major quality of life thing for me (I'll admit to loving to reading profiles and not just to find people to interact with).

**Comment by Ellypse** [comment]
Hi. I like the idea of the mouseover behavior and I will look into implementing it.
In the meantime, the target behavior already exists: if you run the command without an argument `/trp3 show` your current target will be used. Maybe in the meantime can make a macro to /target the mouseover unit and then /targetlasttarget (I can't test that right now, but it sounds possible).

I will add the target, focus, mouseover, targettarget etc tokens resolution in a future update.
Thanks for the suggestion :)

**Comment by Gatheringofravens** [comment]
Doh. Sorry. You're right about the target behavior. 

I whipped this up and it works:

/tar [@mouseover]
/trp3 open
/targetlasttarget

Only caveat being if there was no last target it simply sits on current target.

Thank you very much for the quick and helpful response and also for this wonderful addon, I'm already having quite a fun time with the campaign editor.
