### ISSUE TITLE
Unable to view or edit profile, error on About page

### ISSUE THREAD

**Issue by SekerAsar** [Ellypse/Total-RP-3#97]
### What steps will reproduce the problem?
In a previously established companion pet profile, I had used a picture of the Pet Battle Arcane Storm header... thing. 
### What is the expected output? What do you see instead?
I added " c" (with the space) to the end of the {bit} in an attempt to center the picture. Now I everything appears blank and I am unable to edit the profile. I also tried deleting the profile, but it kept reappearing in the list. I think I must have forgotten how to get it centered and typed the wrong thing, as I feel like I've done so before on different pictures. Though maybe not in a Pet profile.
Here is a screenshot. 

![](http://puu.sh/zBVV3/84fd954ea2.jpg)

### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
No, the bug report seems to only mention TRP.
### What version of Total RP 3 are you using?
Latest I think. 1.3.1
### Was it working in a previous version? If yes, which was the last good one?
Uncertain. Maybe?
### Do you have an error log or screenshot of what happened?
Yes. https://puu.sh/zBUZj/bb42e51611.png
![ss 2018-03-06 at 01 06 33](https://user-images.githubusercontent.com/2637869/37050463-f0d32e8e-2141-11e8-9520-8a235150291c.png)
> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

### Please provide any additional information below.
Sorry I dun bork it 😢 
### If your issue is related to profile data, please provide your data file.
When I try to drag it in here as instructed, it says the file type isn't supported and only takes images, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP. I am certain I am grabbing the .lua and not the .lua.bak. I'll put it in a ZIP instead. 
[totalRP3.zip](https://github.com/Ellypse/Total-RP-3/files/1786198/totalRP3.zip)

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Meorawr** [comment]
At a quick glance, a few of your About fields have an errant `c` inside of the `img` tags:

For example `{img:Interface\\PETBATTLES\\Weather-ArcaneStorm:512:128 c}` in the below (for that specific companion):

```
			["data"] = {
				["IC"] = "INV_Pet_Mouse",
				["TX"] = "{img:Interface\\PETBATTLES\\Weather-ArcaneStorm:512:128 c}\nMaurice is an exceptionally large and intelligent rat. Found in the sewers of Dalaran by Dolores, she presumes he's been mutated from exposure to various alchemical contamination as a result of the more careless Kirin Tor scholars. \n\nFeeling pity for the hapless rodent, Dolores took him in to care for him. She later discovered not only has he grown in size, but in intellect as well! While not quite smart enough to be a fully productive member of society, he readily and capably assists her with her work.\n\nAdditionally she has found that he seems to have resistances to intense weather conditions. From the frigid cold of Northrend, to the intense heat of Uldum: He seems to possess at least minor fire and frost resistances, but is unwilling to subject him to tests to determine the depths of this.",
				["NA"] = "Maurice Tinkertop",
				["TI"] = "Capable Assistant, Dolly's Special Boy",
				["BK"] = 1,
				["v"] = 7,
			},
```

The code should be more bulletproof here though, for sure.

**Comment by Solanya** [comment]
Issue was solved for this specific file, Ellypse has been notified and said "We need a `tonumber()ˋ in the code somewhere I guess."
